image: ruby:2.5.1
before_script:
  - apt-get update -qq && apt-get install -y -qq libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --without staging production
stages:
  - build
  - deploy_staging

job_build:
  stage: build
  script:
    - RACK_ENV=test bundle exec rake

job_deploy_staging:
  stage: deploy_staging
  script:
  - gem install dpl
  - dpl --provider=heroku --app=invernaliaguarabot --api-key=f8946308-e507-41d1-82b6-8ecdb1fed1c6
  only:
  - staging
